/**
 * The app's theme catalogue.
 *
 * `system`, `light` and `dark` are the built-ins whose tokens are authored directly in
 * `src/renderer/src/styles.css`. Every other theme is data: its palette lives here and the
 * matching CSS is generated by {@link themeCss}, so the renderer, the native window chrome
 * and the terminal's ANSI palette all read the same numbers.
 */

export type ThemeId =
  | 'system'
  | 'light'
  | 'dark'
  | 'midnight'
  | 'abyss'
  | 'blueprint'
  | 'admiral'
  | 'nebula'
  | 'solarium'
  | 'evergreen'
  | 'blossom'
  | 'graphite'
  | 'ember'
  | 'ultraviolet'
  | 'magma'
  | 'lagoon'
  | 'fjord'
  | 'claret'
  | 'citrine'
  | 'cappuccino'
  | 'meadow'
  | 'porcelain'
  | 'lavender';

export type ThemeGroup = 'core' | 'navy' | 'futuristic' | 'light' | 'dark';

/** Every color token a theme must define. Keys map to `--kebab-case` custom properties. */
export interface ThemePalette {
  bg: string;
  bgElev: string;
  bgSunken: string;
  bgHover: string;
  bgActive: string;
  fg: string;
  fgMuted: string;
  fgFaint: string;
  border: string;
  borderStrong: string;
  accent: string;
  accentFg: string;
  green: string;
  amber: string;
  red: string;
  blue: string;
  purple: string;
  cyan: string;
  userBubble: string;
  shadow: string;
}

export interface ThemeDescriptor {
  id: ThemeId;
  name: string;
  group: ThemeGroup;
  /** Drives `nativeTheme.themeSource` and the light/dark branch of derived colors. */
  base: 'system' | 'light' | 'dark';
  description: string;
  /** True for themes that add motion; all of it is disabled under `prefers-reduced-motion`. */
  animated?: boolean;
  /** Absent for the three built-ins, whose tokens are authored in styles.css. */
  palette?: ThemePalette;
}

/** Caption colors for the frameless title bar: the theme's `--bg-elev` / `--fg`. */
export interface ThemeChrome {
  color: string;
  symbolColor: string;
}

/**
 * The built-ins' chrome colors. These mirror the `:root` / `[data-theme='dark']` blocks in
 * `src/renderer/src/styles.css`, which is where those two palettes are authored.
 */
const BUILTIN_CHROME: Record<'light' | 'dark', ThemeChrome> = {
  light: { color: '#ffffff', symbolColor: '#1c1c1f' },
  dark: { color: '#191c23', symbolColor: '#e6e7ea' }
};

export const THEMES: ThemeDescriptor[] = [
  { id: 'system', name: 'System', group: 'core', base: 'system', description: 'Follow the OS light/dark setting.' },
  { id: 'light', name: 'Light', group: 'core', base: 'light', description: 'The default neutral light palette.' },
  { id: 'dark', name: 'Dark', group: 'core', base: 'dark', description: 'The default neutral dark palette.' },

  {
    id: 'midnight',
    name: 'Midnight Navy',
    group: 'navy',
    base: 'dark',
    description: 'Deep classic navy with a clear azure accent.',
    palette: {
      bg: '#0f1a2e',
      bgElev: '#16243c',
      bgSunken: '#0a1322',
      bgHover: 'rgba(120, 170, 255, 0.08)',
      bgActive: 'rgba(120, 170, 255, 0.15)',
      fg: '#dbe6f5',
      fgMuted: '#92a6c4',
      fgFaint: '#64789a',
      border: '#1f314f',
      borderStrong: '#2f4569',
      accent: '#4d9dff',
      accentFg: '#06132a',
      green: '#3fd0a0',
      amber: '#f2b757',
      red: '#ff6f7d',
      blue: '#6cb2ff',
      purple: '#a78bfa',
      cyan: '#4fd6e8',
      userBubble: '#1a2b47',
      shadow: '0 10px 40px rgba(2, 8, 20, 0.6)'
    }
  },
  {
    id: 'abyss',
    name: 'Abyss',
    group: 'navy',
    base: 'dark',
    description: 'Navy pushed to near-black, high contrast, aqua accent.',
    palette: {
      bg: '#050b16',
      bgElev: '#0b1524',
      bgSunken: '#01050c',
      bgHover: 'rgba(0, 217, 192, 0.09)',
      bgActive: 'rgba(0, 217, 192, 0.16)',
      fg: '#e8f1ff',
      fgMuted: '#8296b4',
      fgFaint: '#556a89',
      border: '#16263f',
      borderStrong: '#244066',
      accent: '#00d9c0',
      accentFg: '#00201d',
      green: '#2fe08a',
      amber: '#ffc24d',
      red: '#ff5c72',
      blue: '#4aa8ff',
      purple: '#9d7bff',
      cyan: '#22e0e0',
      userBubble: '#0d1b2f',
      shadow: '0 10px 44px rgba(0, 0, 0, 0.75)'
    }
  },
  {
    id: 'blueprint',
    name: 'Blueprint',
    group: 'navy',
    base: 'light',
    description: 'Navy ink on blue-tinted drafting paper — the light side of navy.',
    palette: {
      bg: '#eef3fb',
      bgElev: '#ffffff',
      bgSunken: '#e2eaf7',
      bgHover: 'rgba(16, 37, 74, 0.06)',
      bgActive: 'rgba(16, 37, 74, 0.11)',
      fg: '#10254a',
      fgMuted: '#4a648c',
      fgFaint: '#7e93b4',
      border: '#cad7ea',
      borderStrong: '#a8bcd8',
      accent: '#1b4fa8',
      accentFg: '#ffffff',
      green: '#12795b',
      amber: '#9a6410',
      red: '#b32334',
      blue: '#1f5fc4',
      purple: '#6740b8',
      cyan: '#0e7490',
      userBubble: '#dbe6f8',
      shadow: '0 8px 30px rgba(16, 37, 74, 0.16)'
    }
  },
  {
    id: 'admiral',
    name: 'Admiral',
    group: 'navy',
    base: 'dark',
    description: 'Navy hull, parchment text, brass fittings.',
    palette: {
      bg: '#141d33',
      bgElev: '#1b2743',
      bgSunken: '#0d1526',
      bgHover: 'rgba(224, 179, 84, 0.09)',
      bgActive: 'rgba(224, 179, 84, 0.16)',
      fg: '#ece3d1',
      fgMuted: '#b3a98f',
      fgFaint: '#857f6c',
      border: '#29365a',
      borderStrong: '#3d4d78',
      accent: '#e0b354',
      accentFg: '#211809',
      green: '#8fbd76',
      amber: '#eec96b',
      red: '#e0757f',
      blue: '#7d9fd8',
      purple: '#b295d6',
      cyan: '#6fc2c6',
      userBubble: '#212e4d',
      shadow: '0 10px 40px rgba(6, 12, 26, 0.65)'
    }
  },
  {
    id: 'nebula',
    name: 'Nebula',
    group: 'futuristic',
    base: 'dark',
    animated: true,
    description: 'Futuristic navy-indigo with neon cyan and magenta — animated.',
    palette: {
      bg: '#070b1e',
      bgElev: '#0e1433',
      bgSunken: '#040614',
      bgHover: 'rgba(34, 231, 255, 0.09)',
      bgActive: 'rgba(34, 231, 255, 0.17)',
      fg: '#dff4ff',
      fgMuted: '#8b9ada',
      fgFaint: '#5b64a4',
      border: '#1d2557',
      borderStrong: '#3a46a8',
      accent: '#22e7ff',
      accentFg: '#001a20',
      green: '#3dfaa8',
      amber: '#ffcf5c',
      red: '#ff4d92',
      blue: '#5b8cff',
      purple: '#c77dff',
      cyan: '#22e7ff',
      userBubble: '#141b47',
      shadow: '0 10px 44px rgba(0, 0, 0, 0.7)'
    }
  },
  {
    id: 'solarium',
    name: 'Solarium',
    group: 'light',
    base: 'light',
    description: 'Warm sand paper with a burnt-orange accent.',
    palette: {
      bg: '#fbf5e9',
      bgElev: '#fffdf7',
      bgSunken: '#f2e9d6',
      bgHover: 'rgba(90, 60, 20, 0.06)',
      bgActive: 'rgba(90, 60, 20, 0.12)',
      fg: '#3a2f1e',
      fgMuted: '#7a6a51',
      fgFaint: '#a4937a',
      border: '#e5d8bf',
      borderStrong: '#cbb897',
      accent: '#c25a1c',
      accentFg: '#fffaf2',
      green: '#5b7f31',
      amber: '#a8730a',
      red: '#b53a2b',
      blue: '#2b6a8f',
      purple: '#7d4a9c',
      cyan: '#10788a',
      userBubble: '#f4e6cd',
      shadow: '0 8px 30px rgba(90, 62, 20, 0.18)'
    }
  },
  {
    id: 'evergreen',
    name: 'Evergreen',
    group: 'dark',
    base: 'dark',
    description: 'Dark conifer greens with a mint accent.',
    palette: {
      bg: '#0d1a14',
      bgElev: '#14251c',
      bgSunken: '#08110d',
      bgHover: 'rgba(89, 201, 139, 0.09)',
      bgActive: 'rgba(89, 201, 139, 0.16)',
      fg: '#dce9dd',
      fgMuted: '#8fa993',
      fgFaint: '#62796a',
      border: '#1d3327',
      borderStrong: '#2d4a36',
      accent: '#59c98b',
      accentFg: '#04180d',
      green: '#6fd99a',
      amber: '#d9b45c',
      red: '#e87d7d',
      blue: '#6bb0c8',
      purple: '#a992d8',
      cyan: '#4fc4bd',
      userBubble: '#172a1f',
      shadow: '0 10px 40px rgba(2, 12, 7, 0.6)'
    }
  },
  {
    id: 'blossom',
    name: 'Blossom',
    group: 'light',
    base: 'light',
    description: 'Pale rose paper with a plum accent.',
    palette: {
      bg: '#fdf2f6',
      bgElev: '#ffffff',
      bgSunken: '#f7e5ee',
      bgHover: 'rgba(120, 30, 70, 0.055)',
      bgActive: 'rgba(120, 30, 70, 0.105)',
      fg: '#3d1f30',
      fgMuted: '#7d5468',
      fgFaint: '#a98394',
      border: '#f0d5e0',
      borderStrong: '#dcb0c4',
      accent: '#c2417c',
      accentFg: '#fff5f9',
      green: '#2f8a63',
      amber: '#a9740d',
      red: '#cc3050',
      blue: '#4a63c8',
      purple: '#8b3fbd',
      cyan: '#0d8091',
      userBubble: '#fbe0ec',
      shadow: '0 8px 30px rgba(90, 25, 55, 0.16)'
    }
  },
  {
    id: 'graphite',
    name: 'Graphite',
    group: 'dark',
    base: 'dark',
    description: 'Achromatic dark: no hue in the chrome, only in status colors.',
    palette: {
      bg: '#171717',
      bgElev: '#1f1f1f',
      bgSunken: '#101010',
      bgHover: 'rgba(255, 255, 255, 0.055)',
      bgActive: 'rgba(255, 255, 255, 0.105)',
      fg: '#e8e8e8',
      fgMuted: '#a0a0a0',
      fgFaint: '#6e6e6e',
      border: '#2b2b2b',
      borderStrong: '#3d3d3d',
      accent: '#f2f2f2',
      accentFg: '#141414',
      green: '#9bbfa4',
      amber: '#cfbf92',
      red: '#d99a9a',
      blue: '#a3b4cc',
      purple: '#b8a8c6',
      cyan: '#9fc0c4',
      userBubble: '#262626',
      shadow: '0 10px 40px rgba(0, 0, 0, 0.7)'
    }
  },
  {
    id: 'ember',
    name: 'Ember',
    group: 'dark',
    base: 'dark',
    description: 'Charred warm dark with an ember-orange accent.',
    palette: {
      bg: '#1a1210',
      bgElev: '#241a16',
      bgSunken: '#100a08',
      bgHover: 'rgba(255, 139, 61, 0.09)',
      bgActive: 'rgba(255, 139, 61, 0.16)',
      fg: '#f2dcc4',
      fgMuted: '#b39479',
      fgFaint: '#826853',
      border: '#35251e',
      borderStrong: '#4f382c',
      accent: '#ff8b3d',
      accentFg: '#1d0d02',
      green: '#bccc70',
      amber: '#ffb454',
      red: '#f2635c',
      blue: '#8fa7c2',
      purple: '#c48fb8',
      cyan: '#7fc2b4',
      userBubble: '#2c1f19',
      shadow: '0 10px 40px rgba(0, 0, 0, 0.7)'
    }
  },
  {
    id: 'ultraviolet',
    name: 'Ultraviolet',
    group: 'futuristic',
    base: 'dark',
    description: 'Black-violet with an electric lavender accent.',
    palette: {
      bg: '#120a24',
      bgElev: '#1b1133',
      bgSunken: '#0b0617',
      bgHover: 'rgba(177, 140, 255, 0.09)',
      bgActive: 'rgba(177, 140, 255, 0.16)',
      fg: '#ede7fb',
      fgMuted: '#a89ad0',
      fgFaint: '#7a6ba8',
      border: '#2a1d4d',
      borderStrong: '#43306e',
      accent: '#b18cff',
      accentFg: '#14061f',
      green: '#7be8a8',
      amber: '#ffce6b',
      red: '#ff6b8f',
      blue: '#7d9bff',
      purple: '#c79bff',
      cyan: '#6be0f2',
      userBubble: '#241742',
      shadow: '0 10px 40px rgba(4, 0, 12, 0.7)'
    }
  },
  {
    id: 'magma',
    name: 'Magma',
    group: 'futuristic',
    base: 'dark',
    description: 'Charred black-brown split open by a lava-red accent.',
    palette: {
      bg: '#120808',
      bgElev: '#1c1010',
      bgSunken: '#090404',
      bgHover: 'rgba(255, 71, 87, 0.09)',
      bgActive: 'rgba(255, 71, 87, 0.16)',
      fg: '#f5e0d8',
      fgMuted: '#bd9a90',
      fgFaint: '#8a6a62',
      border: '#33201d',
      borderStrong: '#4e322c',
      accent: '#ff4757',
      accentFg: '#2a0508',
      green: '#9fca6f',
      amber: '#ffb454',
      red: '#ff7f66',
      blue: '#8fa8e0',
      purple: '#cf7fd0',
      cyan: '#6fc9c0',
      userBubble: '#241313',
      shadow: '0 10px 40px rgba(0, 0, 0, 0.75)'
    }
  },
  {
    id: 'lagoon',
    name: 'Lagoon',
    group: 'dark',
    base: 'dark',
    description: 'Deep teal water with a coral-pink accent.',
    palette: {
      bg: '#06222a',
      bgElev: '#0c2f3a',
      bgSunken: '#03161c',
      bgHover: 'rgba(255, 110, 169, 0.08)',
      bgActive: 'rgba(255, 110, 169, 0.15)',
      fg: '#ddf3f2',
      fgMuted: '#8fb5b4',
      fgFaint: '#5f8484',
      border: '#16424c',
      borderStrong: '#245e68',
      accent: '#ff6ea9',
      accentFg: '#2a0715',
      green: '#5fd9a4',
      amber: '#ffcb6b',
      red: '#ff6b6b',
      blue: '#63b7e8',
      purple: '#b39ddb',
      cyan: '#4fd8d0',
      userBubble: '#0e3742',
      shadow: '0 10px 40px rgba(0, 8, 12, 0.7)'
    }
  },
  {
    id: 'fjord',
    name: 'Fjord',
    group: 'dark',
    base: 'dark',
    description: 'Slate-blue nordic dark with a frost-blue accent.',
    palette: {
      bg: '#1e2630',
      bgElev: '#293441',
      bgSunken: '#151b23',
      bgHover: 'rgba(136, 192, 208, 0.09)',
      bgActive: 'rgba(136, 192, 208, 0.16)',
      fg: '#dce5ec',
      fgMuted: '#9aabb9',
      fgFaint: '#6b7d8c',
      border: '#37444f',
      borderStrong: '#4d5f6e',
      accent: '#88c0d0',
      accentFg: '#10252b',
      green: '#a3be8c',
      amber: '#ebcb8b',
      red: '#d08785',
      blue: '#81a1c1',
      purple: '#b48ead',
      cyan: '#8fbcbb',
      userBubble: '#2f3b49',
      shadow: '0 10px 40px rgba(6, 10, 16, 0.65)'
    }
  },
  {
    id: 'claret',
    name: 'Claret',
    group: 'dark',
    base: 'dark',
    description: 'Deep wine-dark maroon with a rose accent.',
    palette: {
      bg: '#210d15',
      bgElev: '#2e1520',
      bgSunken: '#160810',
      bgHover: 'rgba(242, 139, 155, 0.09)',
      bgActive: 'rgba(242, 139, 155, 0.16)',
      fg: '#f4e2e7',
      fgMuted: '#bd93a1',
      fgFaint: '#8c6575',
      border: '#452030',
      borderStrong: '#653247',
      accent: '#f28b9b',
      accentFg: '#2b0a12',
      green: '#9ec98f',
      amber: '#ecc37e',
      red: '#f26d6d',
      blue: '#92a8d8',
      purple: '#c293d8',
      cyan: '#86c5c9',
      userBubble: '#381a26',
      shadow: '0 10px 40px rgba(8, 0, 4, 0.7)'
    }
  },
  {
    id: 'citrine',
    name: 'Citrine',
    group: 'light',
    base: 'light',
    description: 'Pale citron paper with a dark-gold accent.',
    palette: {
      bg: '#faf8ea',
      bgElev: '#fffef5',
      bgSunken: '#f0ecd7',
      bgHover: 'rgba(70, 62, 16, 0.06)',
      bgActive: 'rgba(70, 62, 16, 0.11)',
      fg: '#35321c',
      fgMuted: '#75704a',
      fgFaint: '#9e9878',
      border: '#e2dcc0',
      borderStrong: '#c4bb95',
      accent: '#a07d10',
      accentFg: '#fffdf0',
      green: '#5c7f2e',
      amber: '#8a6808',
      red: '#b5342e',
      blue: '#3568a8',
      purple: '#7a4fa8',
      cyan: '#1d7d8c',
      userBubble: '#f0e9c8',
      shadow: '0 8px 30px rgba(70, 62, 16, 0.16)'
    }
  },
  {
    id: 'cappuccino',
    name: 'Cappuccino',
    group: 'light',
    base: 'light',
    description: 'Frothed-milk warm gray with a coffee-brown accent.',
    palette: {
      bg: '#f3ede6',
      bgElev: '#fbf8f4',
      bgSunken: '#e8dfd5',
      bgHover: 'rgba(70, 48, 32, 0.06)',
      bgActive: 'rgba(70, 48, 32, 0.11)',
      fg: '#3b2f26',
      fgMuted: '#7c695a',
      fgFaint: '#a5917f',
      border: '#ddd0c2',
      borderStrong: '#bfae9c',
      accent: '#8a5a3b',
      accentFg: '#fdf6ef',
      green: '#55793f',
      amber: '#a07424',
      red: '#b04a3c',
      blue: '#4a6d94',
      purple: '#7d5a8c',
      cyan: '#2e7d7d',
      userBubble: '#ece0d2',
      shadow: '0 8px 30px rgba(70, 48, 32, 0.16)'
    }
  },
  {
    id: 'meadow',
    name: 'Meadow',
    group: 'light',
    base: 'light',
    description: 'Soft grass-green paper with a forest accent.',
    palette: {
      bg: '#f0f6e9',
      bgElev: '#fbfdf6',
      bgSunken: '#e2edd6',
      bgHover: 'rgba(36, 51, 28, 0.06)',
      bgActive: 'rgba(36, 51, 28, 0.11)',
      fg: '#24331c',
      fgMuted: '#5c7048',
      fgFaint: '#8a9a76',
      border: '#d0e0bf',
      borderStrong: '#aec494',
      accent: '#3e7a3e',
      accentFg: '#f4faf0',
      green: '#3f8a35',
      amber: '#a87b0a',
      red: '#b83a30',
      blue: '#3a6fae',
      purple: '#7757b0',
      cyan: '#157f88',
      userBubble: '#e0eed0',
      shadow: '0 8px 30px rgba(36, 51, 28, 0.16)'
    }
  },
  {
    id: 'porcelain',
    name: 'Porcelain',
    group: 'light',
    base: 'light',
    description: 'Cool glazed gray-white with a slate-blue accent.',
    palette: {
      bg: '#f1f4f7',
      bgElev: '#fcfdfe',
      bgSunken: '#e4e9ee',
      bgHover: 'rgba(38, 49, 59, 0.06)',
      bgActive: 'rgba(38, 49, 59, 0.11)',
      fg: '#26313b',
      fgMuted: '#5f7080',
      fgFaint: '#8c9aa6',
      border: '#d2dae1',
      borderStrong: '#b2bfc9',
      accent: '#46698c',
      accentFg: '#f5f9fc',
      green: '#3d7f5e',
      amber: '#9a6d14',
      red: '#ab3a44',
      blue: '#3a6f9e',
      purple: '#6f5a9e',
      cyan: '#23747e',
      userBubble: '#e2eaf1',
      shadow: '0 8px 30px rgba(38, 49, 59, 0.15)'
    }
  },
  {
    id: 'lavender',
    name: 'Lavender',
    group: 'light',
    base: 'light',
    description: 'Soft lilac paper with a deep violet accent.',
    palette: {
      bg: '#f4f1fa',
      bgElev: '#fdfcff',
      bgSunken: '#e9e3f4',
      bgHover: 'rgba(47, 37, 64, 0.06)',
      bgActive: 'rgba(47, 37, 64, 0.11)',
      fg: '#2f2540',
      fgMuted: '#6c5f85',
      fgFaint: '#998da9',
      border: '#ddd4ea',
      borderStrong: '#bfb2d6',
      accent: '#7c4dbc',
      accentFg: '#f8f4fd',
      green: '#3f8a5e',
      amber: '#a07414',
      red: '#b83a56',
      blue: '#5560c0',
      purple: '#8a4fc0',
      cyan: '#1d7d92',
      userBubble: '#e9def5',
      shadow: '0 8px 30px rgba(47, 37, 64, 0.16)'
    }
  }
];

export const THEME_IDS: ThemeId[] = THEMES.map((t) => t.id);

export const GROUP_LABELS: Record<ThemeGroup, string> = {
  core: 'Core',
  navy: 'Navy',
  futuristic: 'Futuristic',
  light: 'Light',
  dark: 'Dark'
};

/** Menu/picker order: groups in this order, themes in catalogue order within each group. */
export const GROUP_ORDER: ThemeGroup[] = ['core', 'navy', 'futuristic', 'light', 'dark'];

export function isThemeId(v: unknown): v is ThemeId {
  return typeof v === 'string' && THEME_IDS.includes(v as ThemeId);
}

export function findTheme(id: string): ThemeDescriptor | undefined {
  return THEMES.find((t) => t.id === id);
}

/** The `nativeTheme.themeSource` value a theme needs so OS-drawn surfaces match it. */
export function themeSourceFor(id: string): 'system' | 'light' | 'dark' {
  return findTheme(id)?.base ?? 'system';
}

/**
 * Whether a theme paints a dark UI. `system` has no answer of its own, so callers pass what
 * the OS currently reports.
 */
export function isDarkTheme(id: string, systemDark: boolean): boolean {
  const base = themeSourceFor(id);
  return base === 'system' ? systemDark : base === 'dark';
}

export function chromeFor(id: string, systemDark: boolean): ThemeChrome {
  const t = findTheme(id);
  if (t?.palette) return { color: t.palette.bgElev, symbolColor: t.palette.fg };
  return BUILTIN_CHROME[isDarkTheme(id, systemDark) ? 'dark' : 'light'];
}

/** Three representative colors for a theme swatch, in paint order (base, raised, accent). */
export function swatchFor(id: string, systemDark: boolean): [string, string, string] {
  const p = findTheme(id)?.palette;
  if (p) return [p.bgSunken, p.bgElev, p.accent];
  const dark = isDarkTheme(id, systemDark);
  return dark ? ['#0d0f13', '#191c23', '#8b8bff'] : ['#efeff1', '#ffffff', '#5b5bd6'];
}

function cssName(key: string): string {
  return `--${key.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`)}`;
}

/**
 * Categorical series colours for the analytics charts (`--chart-1` … `--chart-6`), one set per
 * light/dark base rather than per theme: the theme hues are UI accents, and several of them (the
 * desaturated Graphite and Ember sets, the bright dark-theme badges) fail the colour-vision and
 * lightness checks a data palette must pass. This order clears every adjacent-pair check on all
 * catalogue surfaces; the first three slots also pass all-pairs. Light surfaces put slots 3–5 below
 * 3:1 contrast, so every chart ships a legend, hover values and a table view.
 */
export const CHART_SERIES: Record<'light' | 'dark', string[]> = {
  light: ['#2a78d6', '#eb6834', '#1baf7a', '#eda100', '#e87ba4', '#008300'],
  dark: ['#3987e5', '#d95926', '#199e70', '#c98500', '#d55181', '#008300']
};

export function chartSeriesCss(base: 'light' | 'dark'): string[] {
  return CHART_SERIES[base].map((hex, i) => `  --chart-${i + 1}: ${hex};`);
}

/**
 * CSS for every data-driven theme.
 *
 * The selectors are prefixed with `html` so they outrank `:root:not([data-theme='light'])` in
 * `styles.css` regardless of which stylesheet the browser sees first.
 */
export function themeCss(): string {
  const blocks: string[] = [];
  for (const t of THEMES) {
    if (!t.palette) continue;
    const base = t.base === 'light' ? 'light' : 'dark';
    const decls = Object.entries(t.palette).map(([k, v]) => `  ${cssName(k)}: ${v};`);
    decls.unshift(`  color-scheme: ${base};`);
    decls.push(...chartSeriesCss(base));
    blocks.push(`html:root[data-theme='${t.id}'] {\n${decls.join('\n')}\n}`);
  }
  return blocks.join('\n');
}
